### ISSUE TITLE
Proptypes

### ISSUE THREAD

**Issue by LocoBajo** [WildCodeSchool/2023-02-JS-FT-Lyon-P3-Serenity#85]
Dans la page login, lorsque l'on commence à taper dans le champ "mot de passe", une erreur dans la console indique que le composant "FormError" reçoit un prop "errors" de type array, alors qu'il attend apparemment un objet. 

![image](https://github.com/WildCodeSchool/2023-02-JS-FT-Lyon-P3-Serenity/assets/121406911/0c9fd930-ca9d-43e1-b284-c5d20b8e00f7)

**Comment by LightQv** [comment]
Done
